### ISSUE TITLE
.

### ISSUE THREAD

**Issue by 362227** [wvdumper/dumper#10]
I got private_keys, then??

**Comment by wvlover15** [comment]
Try to upload that here well try to check

**Comment by VCDEV1** [comment]
> I got private_keys, then?? ![QQ截图20211215222127](https://user-images.githubusercontent.com/91358231/146203687-b404a385-4625-4a1a-a529-bfb5a723ac9e.jpg)

@362227 can you please tell what did you play after the message Hooks Completed?

Did you edit the script?

**Comment by huliad2022** [comment]
1

**Comment by dausruddin** [comment]
Delete your images.

**Comment by dausruddin** [comment]
@Palyer321 can you kindly delete quoted image?

**Comment by VCDEV1** [comment]
> @Palyer321 can you kindly delete quoted image?

Yeah. But can you say what to do after the hooks completed message.

**Comment by dausruddin** [comment]
@Palyer321 just play any drm protected video. I myself played a local streaming site via chrome.

**Comment by wilsonssss** [comment]
what we got after dump files
![image](https://user-images.githubusercontent.com/4098951/146330905-9276de70-14d0-4c23-9b52-3310cb9049c7.png)

![image](https://user-images.githubusercontent.com/4098951/146330943-0c3b3d54-4bcf-4ddb-9f3d-21b566009080.png)

@dausruddin

**Comment by Mavrick007** [comment]
> what we got after dump files ![image](https://user-images.githubusercontent.com/4098951/146330905-9276de70-14d0-4c23-9b52-3310cb9049c7.png)
> 
> ![image](https://user-images.githubusercontent.com/4098951/146330943-0c3b3d54-4bcf-4ddb-9f3d-21b566009080.png)
> 
> @dausruddin

how did u get this plz
