### ISSUE TITLE
All about luck

### ISSUE THREAD

**Issue by JudgeUAu** [wvdumper/dumper#11]
Tried 4 Devices so far and all are unable to Dump Private Keys

Samsung A20 - Android 9
Samsung S10 - Android 10
Pixel 3a - Android 9
Samsung S21 - Android 11

All Devices only pass Keybox 

I have heard from somone of a successful Dump of Keys on a LG Nexus 5 ..but at this point its all about luck

**Comment by ghost** [comment]
I heard Samsung's seem to struggle. Android 11 doesn't work. Neither does Android 6

**Comment by VCDEV1** [comment]
> Tried 4 Devices so far and all are unable to Dump Private Keys
> 
> Samsung A20 - Android 9 Samsung S10 - Android 10 Pixel 3a - Android 9 Samsung S21 - Android 11
> 
> All Devices only pass Keybox
> 
> I have heard from somone of a successful Dump of Keys on a LG Nexus 5 ..but at this point its all about luck

@JudgeUAu [Here](https://github.com/wvdumper/dumper/issues/9#issue-1080624685) you say you got no files dumped on your [Pixel 3a](https://github.com/wvdumper/dumper/issues/9#issuecomment-994464262) but now you say you got the keyboxes dumped, whereas I still got nothing dumped after the hooks message. I even tried playing video on prime app as you suggested [here](https://github.com/wvdumper/dumper/issues/9#issuecomment-994696732) after the hooks completed message but still I did not get any result!

Please, Really please can you say the exact specific steps you followed?

**Comment by JudgeUAu** [comment]
> 

dont play on prime play it on chrome browser

**Comment by loveyoursupport** [comment]
> Tried 4 Devices so far and all are unable to Dump Private Keys
> 
> Samsung A20 - Android 9 Samsung S10 - Android 10 Pixel 3a - Android 9 Samsung S21 - Android 11
> 
> All Devices only pass Keybox
> 
> I have heard from somone of a successful Dump of Keys on a LG Nexus 5 ..but at this point its all about luck

I can help you if you send me keyboxes

**Comment by FugerZuer** [comment]
> > Tried 4 Devices so far and all are unable to Dump Private Keys
> > Samsung A20 - Android 9 Samsung S10 - Android 10 Pixel 3a - Android 9 Samsung S21 - Android 11
> > All Devices only pass Keybox
> > I have heard from somone of a successful Dump of Keys on a LG Nexus 5 ..but at this point its all about luck
> 
> I can help you if you send me keyboxes

I also have keyboxes, can you help ?
