### ISSUE TITLE
How to see the keys?

### ISSUE THREAD

**Issue by oknchm** [wvdumper/dumper#15]
Using this tool, a `key_dumps` folder appeared containing `client_id.bin` and `private_key.pem` files, also a file named `license_request.bin`. 

1. Are these the only files necessary to get the keys?
2. How do I see the keys? Is another tool needed?

Thank you so much!

**Comment by JD906** [comment]
1) client_id and private_key are the only two files needed yes, but you should rename them, so names matches the old files.
2) Depends what tool you used earlier?

May I ask what device your files is dumped from?

**Comment by oknchm** [comment]
> 1. client_id and private_key are the only two files needed yes, but you should rename them, so names matches the old files.
> 2. Depends what tool you used earlier?

> 

1. What should I rename them? I don't know what are the old files, sorry. Really new to this. :(
2. I used wvdumper to get the client_id and private_key, but I don't know how to use them to get KID:KEY.
(Is that what you're asking? I'm not sure I understand the question. ;;)

**Comment by JD906** [comment]
Have you never used a tool to get KID:KEY ?

**Comment by oknchm** [comment]
> Have you never used a tool to get KID:KEY ?

Oh, so that's what you meant. 😅 I have used tools to get the keys for sure.
I think I know what to rename them now, hope it works.
Thank you!

**Comment by adirt4289** [comment]
HI. what tools i need to use to get the KID:KEY from private_key.pem and client_id.bin?
