### ISSUE TITLE
Android 11

### ISSUE THREAD

**Issue by tuprimafromtomelloso** [wvdumper/dumper#28]
This is a just a research that i did in Android 11.

I managed to go until this.

2021-12-29 10:35:10 AM - Helpers.Scanner - 75 - DEBUG - {
    "from": "android.hardware.drm@1.3-service.widevine",
    "data": "Captured Private Key , expname: dmwdqnvg"
}

BUT

2021-12-29 10:35:10 AM - Helpers.Scanner - 54 - DEBUG - processing private key
2021-12-29 10:35:10 AM - Helpers.Scanner - 102 - ERROR - unable to load private key

any helpful idea people?

**Comment by Filtrattivo** [comment]
Can you post your changes or code?

**Comment by tuprimafromtomelloso** [comment]
https://pastebin.com/Wb4vMNJM

**Comment by Filtrattivo** [comment]
whats your device and android version ?

**Comment by tuprimafromtomelloso** [comment]
Note 9S Lineage OS 18.1 Android 11 CDM 16.0

**Comment by Filtrattivo** [comment]
I tried the code you gave. It started scanning additional functions on my device but could not extract the code. Do you have a resource or explanation on how I can find the additional function codes you posted? you can contact me . tg doomtrap

**Comment by Filtrattivo** [comment]
I tried the code you gave. It started scanning additional functions on my device but could not extract the code. Do you have a source or explanation where I can find additional widevine functions on my device? you can contact me . tg doomtrap

**Comment by jdoe333444** [comment]
You probably didn't read what the author of the project has written in the Readme file. Namely that Android 11+ won't work because of the changing in the OEMcrypto libs which is getting the script broken.

> "**## Known issues
> It seems like Google made some changes in their OEMCrypto library and it broke the script. Further investigation is needed to make it work on Android 11+, feel free to open PRs**."

**Comment by tuprimafromtomelloso** [comment]
This is just a research, the code was modified. It worked in android 10 CDM 15.0 and i was trying it in Android 11 CDM 16.0 but im stuck at that point.

**Comment by JD906** [comment]
A bit hard to help, without seeing the modified code. :)

**Comment by tuprimafromtomelloso** [comment]
https://pastebin.com/tPunRiQG

**Comment by wvlover15** [comment]
> https://pastebin.com/tPunRiQG

Where did you get that modified version?

**Comment by wvlover15** [comment]
> https://pastebin.com/tPunRiQG

So it is connected to this issue before?
![image](https://user-images.githubusercontent.com/96191047/147732807-64fc39bd-1bf5-4c33-88ce-15b409a7136e.png)

**Comment by tuprimafromtomelloso** [comment]
This version is not for an android version under 10 and cdm version under 15, where it works. Trying to make it work in 11-16.0.

Those commands that you say are linked to the device and do not works for another device that is not a Note 9S. Every device have their own. Do not ask about how to get them and from where is this modified version, sorry.

**Comment by wvlover15** [comment]
> This version is not for an android version under 10 and cdm version under 15, where it works. Trying to make it work in 11-16.0.
> 
> Those commands that you say are linked to the device and do not works for another device that is not a Note 9S. Every device have their own. Do not ask about how to get them and from where is this modified version, sorry.

Np. I get it now. I also know how to get it :) I just need to confirm since I don't have yet android 10 just for future use

**Comment by VCDEV1** [comment]
> https://pastebin.com/tPunRiQG

Can you say if this works on redmi note 9s. I have one with android 10. when downgraded to L3 oem crypto version is 15. Did you dump successfully with this? I just want to know because unlocking the bootloader rests everything and it would be a waste if it doesn't work you know :-(

**Comment by wvlover15** [comment]
> > https://pastebin.com/tPunRiQG
> 
> Can you say if this works on redmi note 9s. I have one with android 10. when downgraded to L3 oem crypto version is 15. Did you dump successfully with this? I just want to know because unlocking the bootloader rests everything and it would be a waste if it doesn't work you know :-(

Nope. Only 12 below will work

**Comment by tuprimafromtomelloso** [comment]
> > https://pastebin.com/tPunRiQG
> 
> Can you say if this works on redmi note 9s. I have one with android 10. when downgraded to L3 oem crypto version is 15. Did you dump successfully with this? I just want to know because unlocking the bootloader rests everything and it would be a waste if it doesn't work you know :-(

Yes, that modification can dump cdm 15.0 in Android 10 knowing your KNOWN_DYNAMIC_FUNC. It dumped keys from a Samsung Galaxy A01 Core OEM Crypto API version 15. Didnt try in the Note 9S (im trying Android 11 in this one).

**Comment by Filtrattivo** [comment]
> > https://pastebin.com/tPunRiQG
> 
> Can you say if this works on redmi note 9s. I have one with android 10. when downgraded to L3 oem crypto version is 15. Did you dump successfully with this? I just want to know because unlocking the bootloader rests everything and it would be a waste if it doesn't work you know :-(

With your code, I can access some points on my REDMI 9 device. However, there are still shortcomings. There are probably functions I need to find in the KNOWN_DYNAMIC_FUNC section.

**Comment by tpexer** [comment]
Anyone have that updated script from the pastebin ? i missed that pastebin... its notavailable anymore... i also need to dump on Android 10 on a samsung phone where i can only get the license_request.bin

**Comment by kendyx1** [comment]
@tuprimafromtomelloso please send me modified code, I need it. Please :(

**Comment by FugerZuer** [comment]
Can anyone send me that updated version from pastebin? Contact email: fgeaxgfe@protonmail.com

**Comment by devporter007** [comment]
> https://pastebin.com/tPunRiQG

can someone reup this link, its dead
