### ISSUE TITLE
Doesn't dump anything when playing Widevine content

### ISSUE THREAD

**Issue by ghost** [wvdumper/dumper#29]
It plays the DRM demo video, but it doesn't do anything after that

![afbeelding_2021-12-29_143552](https://user-images.githubusercontent.com/58544833/147667756-84343fa1-a2f1-4ca0-b1a5-836d87346898.png)

**Comment by Mavrick007** [comment]
u need the correct version of python etc

**Comment by ghost** [comment]
> u need the correct version of python etc

I used python 3.9

**Comment by ghost** [comment]
Nvm the custom rom was the issue
