### ISSUE TITLE
.

### ISSUE THREAD

**Issue by ghost** [wvdumper/dumper#41]
.

**Comment by larsk2** [comment]
Look in dumper folder. It will generate files if script completed correctly

**Comment by sahilkundu** [comment]
> Look in dumper folder. It will generate files if script completed correctly

what is the extention of the script

**Comment by sahilkundu** [comment]
How can be use these files 
![Screenshot_2022-04-04_17_37_59](https://user-images.githubusercontent.com/71582663/161540791-08248cc4-71c9-4f58-81ef-782bd8b10c5b.png)
?

**Comment by sahilkundu** [comment]
How can be use these files
![hekki](https://user-images.githubusercontent.com/71582663/161541486-1f400166-b5b9-4aee-bf96-4e708666957a.png)

**Comment by sahilkundu** [comment]
#41
