### ISSUE TITLE
Now I got the dump_keys.py to run

### ISSUE THREAD

**Issue by Dansbo** [wvdumper/dumper#51]
Now I got the script to run.

after hooks I start the widewine content on bitmovin and a lot of data i shown. But I do not get any keys.

I tried to use liboemcrypto.so disabler using magisk but that did not work, so I rebooted into recovery and renamed the file in /system/lib/vendor

But still the keys are not dumped. 

Can I get any help?

**Comment by larsk2** [comment]
What android version are you trying? Think i used late 7 or early 8. I had to try several different before it suddenly worked

**Comment by Dansbo** [comment]
I am using android 9

Where should the keys be dumped? On the device or on in the dumper directory on the computer?

**Comment by larsk2** [comment]
Downgrade Android. On the computer

**Comment by Dansbo** [comment]
Yes I got it to work an another phone with Android 8
