### ISSUE TITLE
Errors running dump_keys.py

### ISSUE THREAD

**Issue by CaptainKoons** [wvdumper/dumper#59]
Hi! 
First of all, I’m a complete noob at programming, so please be patient with me. :-)

I created a virtual android device.
Installed Frida & and put it on the phone.

I ran these commands:
adb.exe shell
su
mv /sdcard/frida-server-16.1.1-android-x86 /data/local/tmp
chmod  +x /data/local/tmp/frida-server-16.1.1-android-x86
/data/local/tmp/frida-server-16.1.1-android-x86

Downloaded dumper and installed the requirements

Then I tried to run dump_keys.py, but got the following errors:

> C:\Users\Tiwar\Downloads\dumper-main
> λ Python dump_keys.py
> Traceback (most recent call last):
>   File "C:\Users\Tiwar\Downloads\dumper-main\dump_keys.py", line 6, in <module>
>     from Helpers.Scanner import Scan
>   File "C:\Users\Tiwar\Downloads\dumper-main\Helpers\Scanner.py", line 7, in <module>
>     from Helpers.wv_proto2_pb2 import SignedLicenseRequest
>   File "C:\Users\Tiwar\Downloads\dumper-main\Helpers\wv_proto2_pb2.py", line 33, in <module>
>     _descriptor.EnumValueDescriptor(
>   File "C:\Users\Tiwar\AppData\Local\Programs\Python\Python311\Lib\site-packages\google\protobuf\descriptor.py", line 796, in __new__
>     _message.Message._CheckCalledFromGeneratedFile()
> TypeError: Descriptors cannot not be created directly.
> If this call came from a _pb2.py file, your generated code is out of date and must be regenerated with protoc >= 3.19.0.
> 
> If you cannot immediately regenerate your protos, some other possible workarounds are:
>  1. Downgrade the protobuf package to 3.20.x or lower.
>  2. Set PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python (but this will use pure-Python parsing and will be much slower).
> 
> More information: https://developers.google.com/protocol-buffers/docs/news/2022-05-06#python-updates
> 

Any ideas what I’m doing wrong?
Many thanks in advance!
CK

**Comment by CaptainKoons** [comment]
Got help from another source.
If anybody has the same problem... I needed to run the following installation before running dump_keys.py:

> pip install protobuf==3.20.3

**Comment by mantaairo** [comment]
> Got help from another source. If anybody has the same problem... I needed to run the following installation before running dump_keys.py:
> 
> > pip install protobuf==3.20.3

Hi, I had these errors with protobuf==3.19 in requirements.txt.

![Image](https://github.com/user-attachments/assets/28e24646-70fd-4a74-94cf-f1525eca47bc)

The errors have been reduced, but I still have these ones and I don't get the key_dumps.

![Image](https://github.com/user-attachments/assets/43072edb-c7a5-4649-a00f-605f4e97f261)

Could you please help me fix it?
